export const GRIDDLE_RECIPES = [
  {
    name: 'Griddle Smash Burgers & Onions',
    description: 'Crispy-edged smash burgers with caramelized onions and toasted buns, cooked together on the outdoor griddle.',
    servings: 6,
    prep_time_min: 15,
    cook_time_min: 20,
    calories: 610,
    protein_g: 39,
    carbs_g: 34,
    fat_g: 34,
    ingredients: [
      { item: 'Ground beef (80/20)', qty: 2, unit: 'lb', section: 'Meat & Seafood' },
      { item: 'Yellow onions, thinly sliced', qty: 2, unit: '', section: 'Produce' },
      { item: 'Cheddar cheese slices', qty: 6, unit: '', section: 'Dairy & Eggs' },
      { item: 'Burger buns', qty: 6, unit: '', section: 'Bread' },
      { item: 'Pickles', qty: 1, unit: 'jar', section: 'Pantry' },
      { item: 'Burger sauce', qty: 0.5, unit: 'cup', section: 'Pantry' },
      { item: 'Avocado oil', qty: 2, unit: 'tbsp', section: 'Pantry' },
      { item: 'Salt & pepper', qty: 0, unit: 'to taste', section: 'Pantry' },
    ],
    steps: [
      'Preheat the griddle with one zone on medium and one on medium-high.',
      'Divide beef into 12 loose balls; do not pack them tightly.',
      'Oil the medium zone and cook onions with a pinch of salt until browned and soft.',
      'Place beef balls on the hot zone, cover with parchment, and smash very thin. Season well.',
      'Cook 2–3 minutes until deeply browned, scrape and flip, then add cheese.',
      'Stack two patties per burger, toast buns on the griddle, and assemble with onions, pickles, and sauce.',
    ],
    tags: ['griddle', 'kid-friendly', 'high-protein', 'summer', 'costco-friendly'],
    starred: false,
  },
  {
    name: 'Griddle Chicken Fried Rice',
    description: 'A family-size fried rice with chicken, vegetables, and eggs that uses the whole flat-top surface.',
    servings: 6,
    prep_time_min: 20,
    cook_time_min: 20,
    calories: 520,
    protein_g: 42,
    carbs_g: 58,
    fat_g: 13,
    ingredients: [
      { item: 'Boneless skinless chicken thighs, diced', qty: 2, unit: 'lb', section: 'Meat & Seafood' },
      { item: 'Cooked rice, chilled', qty: 6, unit: 'cups', section: 'Pantry' },
      { item: 'Frozen peas and carrots', qty: 3, unit: 'cups', section: 'Frozen' },
      { item: 'Eggs', qty: 4, unit: '', section: 'Dairy & Eggs' },
      { item: 'Green onions, sliced', qty: 1, unit: 'bunch', section: 'Produce' },
      { item: 'Soy sauce', qty: 0.33, unit: 'cup', section: 'Pantry' },
      { item: 'Sesame oil', qty: 2, unit: 'tbsp', section: 'Pantry' },
      { item: 'Avocado oil', qty: 3, unit: 'tbsp', section: 'Pantry' },
      { item: 'Garlic, minced', qty: 1, unit: 'tbsp', section: 'Produce' },
    ],
    steps: [
      'Preheat the griddle to medium-high and oil the surface.',
      'Cook chicken in one zone until browned and 165°F inside; move it to a cooler zone.',
      'Cook peas and carrots with garlic until hot, then move beside the chicken.',
      'Scramble eggs on a clean section of the griddle.',
      'Add chilled rice, spread it thin, and let it crisp before tossing.',
      'Combine everything, season with soy sauce and sesame oil, and finish with green onions.',
    ],
    tags: ['griddle', 'kid-friendly', 'high-protein', 'meal-prep', 'costco-friendly'],
    starred: false,
  },
  {
    name: 'Griddle Steak Fajitas',
    description: 'Sizzling steak, peppers, and onions cooked fast on the griddle and served family-style with warm tortillas.',
    servings: 6,
    prep_time_min: 20,
    cook_time_min: 15,
    calories: 540,
    protein_g: 42,
    carbs_g: 43,
    fat_g: 22,
    ingredients: [
      { item: 'Flank or skirt steak, sliced thin', qty: 2, unit: 'lb', section: 'Meat & Seafood' },
      { item: 'Bell peppers, sliced', qty: 4, unit: '', section: 'Produce' },
      { item: 'Yellow onions, sliced', qty: 2, unit: '', section: 'Produce' },
      { item: 'Large flour tortillas', qty: 12, unit: '', section: 'Bread' },
      { item: 'Fajita seasoning', qty: 3, unit: 'tbsp', section: 'Pantry' },
      { item: 'Limes', qty: 3, unit: '', section: 'Produce' },
      { item: 'Avocado oil', qty: 3, unit: 'tbsp', section: 'Pantry' },
      { item: 'Shredded cheese', qty: 2, unit: 'cups', section: 'Dairy & Eggs' },
      { item: 'Salsa', qty: 1, unit: 'jar', section: 'Pantry' },
    ],
    steps: [
      'Preheat the griddle to high heat and oil lightly.',
      'Season steak with fajita seasoning and half the lime juice.',
      'Cook peppers and onions on one side until browned but still crisp.',
      'Spread steak in a single layer on the hot side and cook quickly, turning once.',
      'Combine steak and vegetables, squeeze over remaining lime juice, and warm tortillas on a cooler zone.',
      'Serve immediately with cheese and salsa.',
    ],
    tags: ['griddle', 'high-protein', 'quick', 'summer', 'costco-friendly'],
    starred: false,
  },
  {
    name: 'Griddle Hibachi Chicken & Vegetables',
    description: 'Hibachi-style chicken, zucchini, mushrooms, and broccoli with a simple garlic-soy butter sauce.',
    servings: 6,
    prep_time_min: 20,
    cook_time_min: 20,
    calories: 430,
    protein_g: 45,
    carbs_g: 27,
    fat_g: 16,
    ingredients: [
      { item: 'Boneless skinless chicken breasts, cubed', qty: 2.5, unit: 'lb', section: 'Meat & Seafood' },
      { item: 'Zucchini, sliced', qty: 3, unit: '', section: 'Produce' },
      { item: 'Mushrooms, sliced', qty: 16, unit: 'oz', section: 'Produce' },
      { item: 'Broccoli florets', qty: 2, unit: 'lb', section: 'Produce' },
      { item: 'Butter', qty: 4, unit: 'tbsp', section: 'Dairy & Eggs' },
      { item: 'Soy sauce', qty: 0.25, unit: 'cup', section: 'Pantry' },
      { item: 'Garlic, minced', qty: 1, unit: 'tbsp', section: 'Produce' },
      { item: 'Sesame oil', qty: 1, unit: 'tbsp', section: 'Pantry' },
      { item: 'Cooked rice', qty: 4, unit: 'cups', section: 'Pantry' },
    ],
    steps: [
      'Preheat the griddle to medium-high and melt half the butter with a little sesame oil.',
      'Cook chicken in a single layer until browned and 165°F inside.',
      'Cook broccoli with a splash of water under a griddle dome for 2–3 minutes.',
      'Add zucchini and mushrooms; cook until browned and tender-crisp.',
      'Combine chicken and vegetables, then toss with remaining butter, garlic, and soy sauce.',
      'Warm or crisp the cooked rice on the griddle and serve alongside.',
    ],
    tags: ['griddle', 'kid-friendly', 'high-protein', 'veggie-heavy', 'costco-friendly'],
    starred: false,
  },
  {
    name: 'Griddle Breakfast for Dinner',
    description: 'Pancakes, eggs, bacon, and breakfast sausage cooked in zones for an easy family breakfast-for-dinner night.',
    servings: 6,
    prep_time_min: 15,
    cook_time_min: 25,
    calories: 650,
    protein_g: 34,
    carbs_g: 55,
    fat_g: 33,
    ingredients: [
      { item: 'Pancake mix', qty: 3, unit: 'cups', section: 'Pantry' },
      { item: 'Eggs', qty: 12, unit: '', section: 'Dairy & Eggs' },
      { item: 'Bacon', qty: 1, unit: 'lb', section: 'Meat & Seafood' },
      { item: 'Breakfast sausage links', qty: 1, unit: 'lb', section: 'Meat & Seafood' },
      { item: 'Milk', qty: 2, unit: 'cups', section: 'Dairy & Eggs' },
      { item: 'Butter', qty: 4, unit: 'tbsp', section: 'Dairy & Eggs' },
      { item: 'Maple syrup', qty: 1, unit: 'bottle', section: 'Pantry' },
      { item: 'Fresh berries', qty: 2, unit: 'pints', section: 'Produce' },
    ],
    steps: [
      'Preheat two griddle zones: medium-low for pancakes and eggs, medium for meat.',
      'Cook bacon and sausage first, turning until browned and fully cooked; move to a warm zone.',
      'Mix pancake batter and cook pancakes on the medium-low zone until bubbles form, then flip.',
      'Scramble eggs with a little butter on a clean section of the griddle.',
      'Serve everything family-style with berries and maple syrup.',
    ],
    tags: ['griddle', 'kid-friendly', 'family-friendly', 'breakfast-for-dinner', 'costco-friendly'],
    starred: false,
  },
]
